spring.application.name: continuum-api-server
spring:
  datasource:
    url: ${CONTINUUM_DB_URL:jdbc:postgresql://localhost:35432/continuum}
    username: ${CONTINUUM_DB_USERNAME:continuum_owner}
    password: ${CONTINUUM_DB_PASSWORD:continuum-test-password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
temporal:
  connection:
    target: ${TEMPORAL_SERVER_ADDRESS:localhost:7233}
    namespace: ${TEMPORAL_NAMESPACE:default}
spring.ai.mcp.server:
  name: continuum-node-registry-mcp-server
  version: 1.0.0
  type: SYNC
  protocol: STREAMABLE
  annotation-scanner:
    enabled: true
continuum.core:
  api-server:
    cache-directory-base-path: ${CONTINUUM_CACHE_DIRECTORY:./.continuum-cache/workflow-data}
    storage:
      type: ${CONTINUUM_STORAGE_TYPE:minio}
      bucket-name: ${CONTINUUM_CACHE_BUCKET_NAME:continuum-worker-storage}
      bucket-region: ${CONTINUUM_CACHE_BUCKET_REGION:us-east-2}
      bucket-base-path: ${CONTINUUM_CACHE_BUCKET_BASE_PATH:workflow-data}
      minio:
        endpoint: ${CONTINUUM_MINIO_ENDPOINT:http://localhost:39000}
        access-key: ${CONTINUUM_MINIO_USERNAME:minioadmin}
        secret-key: ${CONTINUUM_MINIO_PASSWORD:minioadmin}

springdoc:
  swagger-ui:
    config-url: ../v3/api-docs/swagger-config
    url: ../v3/api-docs
